#!/usr/bin/env php
<?php

/**
 * COMPREHENSIVE PERMISSION & ROUTER DIAGNOSIS
 * =============================================
 * Script ini mengecek seluruh permission flow dari backend ke frontend
 */

require __DIR__.'/vendor/autoload.php';
$app = require_once __DIR__.'/bootstrap/app.php';
$kernel = $app->make('Illuminate\Contracts\Console\Kernel');
$kernel->bootstrap();

$superAdmin = \App\Models\User::where('email', 'admin@admin.com')->first();
$viewer = \App\Models\User::where('email', 'andiandnovee@gmail.com')->first();

echo "\n";
echo "╔════════════════════════════════════════════════════════════════════════════════╗\n";
echo "║      COMPREHENSIVE PERMISSION & ROUTERLINK DIAGNOSIS                           ║\n";
echo "╚════════════════════════════════════════════════════════════════════════════════╝\n\n";

// SECTION 1: Backend Response Format
echo "████████ SECTION 1: BACKEND LOGIN RESPONSE ████████\n\n";

$loginResponse = [
    'success' => true,
    'message' => 'Login successful',
    'data' => [
        'token' => 'sample_token_xxx...',
        'user' => [
            'id' => $superAdmin->id,
            'name' => $superAdmin->name,
            'email' => $superAdmin->email,
            'avatar' => $superAdmin->avatar,
            'provider' => $superAdmin->provider,
            'roles' => $superAdmin->role_names,
            'permissions' => $superAdmin->permission_names,
        ],
    ],
];

echo "✓ HTTP 201\n";
echo "✓ Content-Type: application/json\n";
echo json_encode($loginResponse, JSON_PRETTY_PRINT)."\n\n";

echo "Checklist Backend:\n";
echo '  [✓] user.id = '.$superAdmin->id."\n";
echo '  [✓] user.name = '.$superAdmin->name."\n";
echo '  [✓] user.email = '.$superAdmin->email."\n";
echo '  [✓] user.roles = '.json_encode($superAdmin->role_names)."\n";
echo '  [✓] user.permissions = '.json_encode($superAdmin->permission_names)."\n";
echo "  [✓] TOKEN = generated by Sanctum\n\n";

// SECTION 2: Frontend LocalStorage
echo "\n████████ SECTION 2: FRONTEND LOCALSTORAGE ████████\n\n";

$tokenStorage = 'Bearer_token_xxx...';
$userStorage = [
    'id' => $superAdmin->id,
    'name' => $superAdmin->name,
    'email' => $superAdmin->email,
    'avatar' => $superAdmin->avatar,
    'provider' => $superAdmin->provider,
    'roles' => $superAdmin->role_names,
    'permissions' => $superAdmin->permission_names,
];

echo "localStorage['token'] = '".substr($tokenStorage, 0, 20)."...'\n";
echo "localStorage['user'] = ".json_encode($userStorage, JSON_PRETTY_PRINT)."\n\n";

echo "Checklist Frontend (localStorage):\n";
echo "  [ ] Apakah token ada? (check: localStorage.getItem('token'))\n";
echo "  [ ] Apakah user ada? (check: localStorage.getItem('user'))\n";
echo "  [ ] Apakah permissions array ada? (check: JSON.parse(localStorage.getItem('user')).permissions)\n";
echo "  [ ] Apakah permissions bukan null/undefined/empty?\n\n";

// SECTION 3: Pinia Store State
echo "\n████████ SECTION 3: PINIA AUTH STORE STATE ████████\n\n";

echo "useAuthStore() state structure:\n";
echo "{\n";
echo "  token: '".substr($tokenStorage, 0, 20)."...',\n";
echo "  user: {\n";
echo '    id: '.$superAdmin->id.",\n";
echo "    name: '".$superAdmin->name."',\n";
echo "    email: '".$superAdmin->email."',\n";
echo '    roles: '.json_encode($superAdmin->role_names).",\n";
echo '    permissions: '.json_encode($superAdmin->permission_names).",\n";
echo "  },\n";
echo "  isAuthenticated: computed(() => !!token.value),\n";
echo "  userRoles: computed(() => user.value?.roles || []),\n";
echo "  userPermissions: computed(() => user.value?.permissions || []),\n";
echo "}\n\n";

echo "Checklist useAuthStore:\n";
echo '  [ ] authStore.user.permissions = '.json_encode($superAdmin->permission_names)."\n";
echo '  [ ] authStore.userPermissions = '.json_encode($superAdmin->permission_names)."\n";
echo "  [ ] AUTH STORE ISSUE: userPermissions kosong/undefined?\n\n";

// SECTION 4: usePermission Composable
echo "\n████████ SECTION 4: USEPERMISSION COMPOSABLE ████████\n\n";

echo "Function: hasPermission(permission_string)\n";
echo "Logic: auth.userPermissions.includes(permission)\n\n";

$testPerms = ['view users', 'view roles', 'view settings'];
echo "Test Results:\n";
foreach ($testPerms as $perm) {
    $exists = in_array($perm, $superAdmin->permission_names);
    echo '  '.($exists ? '✓' : '✗')." hasPermission('".$perm."') = ".($exists ? 'true' : 'false')."\n";
}

echo "\nUsePermission ISSUE IF:\n";
echo "  - auth.userPermissions is empty/undefined\n";
echo "  - hasPermission() always returns false\n";
echo "  - authStore.user.permissions is null\n\n";

// SECTION 5: AppSidebar Rendering
echo "\n████████ SECTION 5: APPSIDEBAR MENU FILTERING ████████\n\n";

$menuItems = [
    ['path' => '/dashboard', 'label' => 'Dashboard', 'permission' => null],
    ['path' => '/users', 'label' => 'Users', 'permission' => 'view users'],
    ['path' => '/roles', 'label' => 'Roles', 'permission' => 'view roles'],
    ['path' => '/settings', 'label' => 'Settings', 'permission' => 'view settings'],
];

echo "Filter Logic:\n";
echo "  const menuItems = computed(() => {\n";
echo "    return allMenuItems.filter((item) => {\n";
echo "      if (item.permission) {\n";
echo "        return hasPermission(item.permission)  // ← KEY FUNCTION\n";
echo "      }\n";
echo "      return true  // Items tanpa permission always visible\n";
echo "    })\n";
echo "  })\n\n";

echo "Expected vs Actual:\n";
foreach ($menuItems as $item) {
    $shouldShow = ! $item['permission'] || in_array($item['permission'], $superAdmin->permission_names);
    echo '  '.($shouldShow ? '✓' : '✗').' '.$item['label'].' ('.($item['permission'] ?: 'no permission').")\n";
    echo '       Expected: '.($shouldShow ? 'VISIBLE' : 'HIDDEN')."\n";
    echo "       Actual: ???\n\n";
}

// SECTION 6: RouterLink Generation
echo "\n████████ SECTION 6: ROUTERLINK GENERATION ████████\n\n";

echo "Vue Template:\n";
echo "  <li v-for=\"item in menuItems\">\n";
echo "    <RouterLink :to=\"item.path\">\n";
echo "      {{ item.label }}\n";
echo "    </RouterLink>\n";
echo "  </li>\n\n";

echo "If menuItems filter is working correctly:\n";
for ($i = 0; $i < count($menuItems); $i++) {
    $item = $menuItems[$i];
    $shouldShow = ! $item['permission'] || in_array($item['permission'], $superAdmin->permission_names);
    if ($shouldShow) {
        echo "  <li>\n";
        echo '    <RouterLink to="'.$item['path']."\">\n";
        echo '      '.$item['label']."\n";
        echo "    </RouterLink>\n";
        echo "  </li>\n";
    }
}

echo "\n✓ EXPECTED: 4 RouterLinks rendered (/dashboard, /users, /roles, /settings)\n";
echo "✗ ACTUAL: Only /dashboard appears?\n\n";

// SECTION 7: Problem Diagnosis Decision Tree
echo "\n████████ SECTION 7: PROBLEM DIAGNOSIS TREE ████████\n\n";

echo "Use this decision tree to find the problem:\n\n";

echo "Q1: In browser console, is authStore.userPermissions empty?\n";
echo "├─ YES → Problem in FRONTEND\n";
echo "│  ├─ Check: Is localStorage['user'].permissions = null?\n";
echo "│  │  ├─ YES → Backend not sending permissions (but we verified it is!)\n";
echo "│  │  └─ NO → Firefox is parsing JSON wrong?\n";
echo "│  └─ Check: Is auth store computed property wrong?\n";
echo "│     └─ Computed: () => user.value?.permissions || []\n";
echo "└─ NO → Problem in AppSidebar OR hasPermission()\n";
echo "   ├─ Check: Does hasPermission('view users') return true?\n";
echo "   │  ├─ YES → menuItems filter is broken\n";
echo "   │  └─ NO → hasPermission() logic is wrong\n";
echo "   └─ Check: Can you manually see menuItems?\n";
echo "      └─ <script>console.log(Array from allMenuItems, menuItems)</script>\n\n";

// SECTION 8: Quick Test Commands
echo "\n████████ SECTION 8: BROWSER CONSOLE COMMANDS ████████\n\n";

echo "Copy & paste these in browser console (F12 > Console tab):\n\n";

echo "// Check localStorage\n";
echo "localStorage.user\n";
echo "JSON.parse(localStorage.user).permissions\n\n";

echo "// Check auth store\n";
echo "const { useAuthStore } = await import('@/stores/auth')\n";
echo "const auth = useAuthStore()\n";
echo "auth.user\n";
echo "auth.userPermissions\n";
echo "auth.isAuthenticated\n\n";

echo "// Check hasPermission  \n";
echo "const { usePermission } = await import('@/composables/usePermission')\n";
echo "const { hasPermission } = usePermission()\n";
echo "hasPermission('view users')\n";
echo "hasPermission('view roles')\n";
echo "hasPermission('view settings')\n\n";

// SECTION 9: Summary
echo "\n████████ SECTION 9: SUMMARY CHECKLIST ████████\n\n";

echo "Backend Status:\n";
echo "  [✓] User model has permission_names attribute\n";
echo "  [✓] AuthController returns permissions in login & me endpoints\n";
echo "  [✓] User->permission_names returns all 11 permissions\n";
echo "  [✓] Super admin has all permissions (verified)\n\n";

echo "Frontend Status to DEBUG:\n";
echo "  [ ] localStorage['user'].permissions is not empty\n";
echo "  [ ] authStore.user.permissions contains permissions\n";
echo "  [ ] authStore.userPermissions computed property works\n";
echo "  [ ] hasPermission() function returns true for valid permissions\n";
echo "  [ ] AppSidebar menuItems filter executes correctly\n";
echo "  [ ] RouterLinks are generated for all allowed items\n\n";

echo "💡 TIP: Open /debug page in browser and check the UI output\n";
echo "💡 TIP: Click 'Log to Console' button to see full debug info\n";
echo "💡 TIP: If userPermissions shows empty, check localStorage in DevTools\n\n";
